export enum E_ErrorResponse {
    "No Error",
    "Invalid JSON payload",
    "Missing X-BTK-APIKEY",
    "Invalid API key",
    "API pending for activation",
    "IP not allowed",
    "Missing / invalid signature",
    "Missing timestamp",
    "Invalid timestamp",
    "Invalid user",
    "Invalid parameter",
    "Invalid symbol",
    "Invalid amount",
    "Invalid rate",
    "Improper rate",
    "Amount too low",
    "Failed to get balance",
    "Wallet is empty",
    "Insufficient balance",
    "Failed to insert order into db",
    "Failed to deduct balance",
    "Invalid order for cancellation",
    "Invalid side",
    "Failed to update order status",
    "Invalid order for lookup",
    "KYC level 1 is required to proceed",
    "Limit exceeds" = 30,
    "Pending withdrawal exists" = 40,
    "Invalid currency for withdrawal",
    "Address is not in whitelist",
    "Failed to deduct crypto",
    "Failed to create withdrawal record",
    "Nonce has to be numeric",
    "Invalid nonce",
    "Withdrawal limit exceeds",
    "Invalid bank account",
    "Bank limit exceeds",
    "Pending withdrawal exists ",
    "Withdrawal is under maintenance",
    "Server error (please contact support)" = 90,
}

